# Generated by Django 3.1.7 on 2021-09-29 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('today', '0002_post_bookmark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmark_user',
        ),
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
